### PR TITLE
Using PyTorch cpp_extension helper

### PR DESCRIPTION
**Pull request by mjstevens777**
Hello, and thanks for putting together this nice code base. I wrote a slight modification to use [PyTorch C++ JIT extensions](https://pytorch.org/tutorials/advanced/cpp_extension.html#jit-compiling-extensions). The benefit of this is that there is no extra step to run before running the code. The drawback is a few seconds of compilation time when the model is imported, and probably incompatibility with earlier pytorch versions (I only tested 0.4). Please let me know if you are interested in incorporating this change and if there is any adjustments you would like me to make.

The main changes I made were:
- Switching from TH and THC to ATen
- Adding pybind11 wrappers instead of using FFI
- Adding the JIT compilation step to the python wrappers

I have also created a pip-installable version of this library if you are interested in that:
- [Diff](https://github.com/multimodallearning/pytorch-mask-rcnn/compare/master...mjstevens777:feat/package?expand=1)
- [Tree](https://github.com/mjstevens777/pytorch-mask-rcnn/tree/feat/package)

### CODE REVIEW

**Comment by lxtGH** [comment]
Hi! Nice work, Have you try this module in your experiments, did it work as the previous one ?? what about the speed @mjstevens777

**Comment by mjstevens777** [comment]
Yes, I tested it and it worked the same as far as I could tell. I only changed the wrapper, not the implementation, so the speed and functionality should be the same.

**Comment by lxtGH** [comment]
@mjstevens777 But I met this error when I use your repo(feat/build) when I import the module
Traceback (most recent call last):
  File "/home/lxt/env/pytorch.4.0/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 576, in _build_extension_module
    ['ninja', '-v'], stderr=subprocess.STDOUT, cwd=build_directory)
  File "/home/lxt/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/lxt/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_jit.py", line 1, in <module>
    from roialign.roi_align.crop_and_resize import CropAndResizeFunction
  File "/home/lxt/study/pytorch-mask-rcnn/roialign/roi_align/crop_and_resize.py", line 11, in <module>
    os.path.join(os.path.dirname(__file__), "src/crop_and_resize.cpp")
  File "/home/lxt/env/pytorch.4.0/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 501, in load
    _build_extension_module(name, build_directory)
  File "/home/lxt/env/pytorch.4.0/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 582, in _build_extension_module
    name, error.output.decode()))
RuntimeError: Error building extension 'cpu_crop_and_resize': [1/2] c++ -MMD -MF crop_and_resize.o.d -DTORCH_EXTENSION_NAME=cpu_crop_and_resize -I/home/lxt/env/pytorch.4.0/lib/python3.6/site-packages/torch/lib/include -I/home/lxt/env/pytorch.4.0/lib/python3.6/site-packages/torch/lib/include/TH -I/home/lxt/env/pytorch.4.0/lib/python3.6/site-packages/torch/lib/include/THC -I/home/lxt/env/pytorch.4.0/include/python3.6m -fPIC -std=c++11 -c /home/lxt/study/pytorch-mask-rcnn/roialign/roi_align/src/crop_and_resize.cpp -o crop_and_resize.o
FAILED: crop_and_resize.o 
c++ -MMD -MF crop_and_resize.o.d -DTORCH_EXTENSION_NAME=cpu_crop_and_resize -I/home/lxt/env/pytorch.4.0/lib/python3.6/site-packages/torch/lib/include -I/home/lxt/env/pytorch.4.0/lib/python3.6/site-packages/torch/lib/include/TH -I/home/lxt/env/pytorch.4.0/lib/python3.6/site-packages/torch/lib/include/THC -I/home/lxt/env/pytorch.4.0/include/python3.6m -fPIC -std=c++11 -c /home/lxt/study/pytorch-mask-rcnn/roialign/roi_align/src/crop_and_resize.cpp -o crop_and_resize.o
In file included from /home/lxt/study/pytorch-mask-rcnn/roialign/roi_align/src/crop_and_resize.cpp:1:0:
/home/lxt/study/pytorch-mask-rcnn/roialign/roi_align/src/crop_and_resize.h:2:5: error: variable or field ‘crop_and_resize_forward’ declared void
     at::Tensor image,
     ^
/home/lxt/study/pytorch-mask-rcnn/roialign/roi_align/src/crop_and_resize.h:2:5: error: ‘at’ has not been declared
/home/lxt/study/pytorch-mask-rcnn/roialign/roi_align/src/crop_and_resize.h:3:5: error: ‘at’ has not been declared
     at::Tensor boxes,      // [y1, x1, y2, x2]
     ^
/home/lxt/study/pytorch-mask-rcnn/roialign/roi_align/src/crop_and_resize.h:4:5: error: ‘at’ has not been declared
     at::Tensor box_index,    // range in [0, batch_size)

**Comment by mjstevens777** [comment]
I forgot an `include <torch/torch.h>`. Also, it looks like I made some other errors. I am going to check the code again on GPU to make sure everything is working properly.

EDIT: It's working for me on GPU as well.

**Pull request closed without merging**
